### ISSUE TITLE
assert_equals should do expected == actual instead of actual == expected

### ISSUE THREAD

**Issue by namedots** [codewars/python-test-framework#26]
the expected value's == implementation should be prefered over whatever the solver returned

**Comment by Blind4Basics** [comment]
Talking about forbidding the `__eq__` cheat?
Last time I checked, that didn't change anything because when the type check fails in the "builtin `__eq__`" (`expected == user_value`), it tries to delegate to `user_value == expected`.
I just did a quick check and it seems the behavior is still the same.

=> Am I missing something?

**Comment by namedots** [comment]
I had a couple other cases in mind as well (for example numpy arrays producing confusing error messages when a comparison result is converted to bool), but it all turns out irrelevant.

I wasn't aware that `NotImplemented` is returned by various built in implementations of equals in order to try the other way around, I figured it was `False`, but, no.

Thank you for clearing that up.
